name: Scan Bilibili Emoji
on:
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scan emoji
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          ACCOUNT_DB_URI: ${{ secrets.ACCOUNT_DB_URI }}
          SCAN_CONFIG: ${{ secrets.SCAN_CONFIG }}
        run: python script/main.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]
          then
            echo "No changes to commit"
          else
            git commit -m "Update emoji list at $(date '+%Y.%m.%d %H:%M:%S')(UTC+8)"
            git push
          fi

