name: Scan Bilibili Emoji
on:
  workflow_dispatch:
  push:
    branches:
      master
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "list/**"
  schedule:
    - cron: "15 4,15 * * *"
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scan emoji
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SCAN_CONFIG: ${{ secrets.SCAN_CONFIG }}
        run: python script/main.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]
          then
            echo "No changes to commit"
          else
            git commit -m "Update emoji list at $(date '+%Y.%m.%d %H:%M:%S')(UTC+8)"
            git push
          fi

